{{- if (not .Values.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mariadb.fullname" . }}
  labels:
    app: "{{ template "mariadb.name" . }}"
    chart: "{{ template "rod3.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if .Values.mariadb.rootUser.password }}
  mariadb-root-password: "{{ .Values.mariadb.rootUser.password | b64enc }}"
  {{- else if (not .Values.mariadb.rootUser.forcePassword) }}
  mariadb-root-password: "{{ randAlphaNum 10 | b64enc }}"
  {{ else }}
  mariadb-root-password: {{ required "A MariaDB Root Password is required!" .Values.mariadb.rootUser.password }}
  {{- end }}
  {{- if .Values.db.user }}
  {{- if .Values.db.password }}
  mariadb-password: "{{ .Values.db.password | b64enc }}"
  {{- else if (not .Values.db.forcePassword) }}
  mariadb-password: "{{ randAlphaNum 10 | b64enc }}"
  {{- else }}
  mariadb-password: {{ required "A MariaDB Database Password is required!" .Values.db.password }}
  {{- end }}
  {{- end }}
{{- end }}
