apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mariadb.selectorLabels" . | nindent 6 }}
  serviceName: {{ template "mariadb.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "mariadb.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "rod3.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: mysql-persistent-storage

      containers:
        - name: {{ .Chart.Name }}-db
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
          - configMapRef:
              name: {{ template "rod3.fullname" . }}-locale
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "mariadb.secretName" . }}
                key: mariadb-root-password
          {{- if .Values.db.user }}
          - name: MYSQL_USER
            value: "{{ .Values.db.user }}"
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "mariadb.secretName" . }}
                key: mariadb-password
          {{- end }}
          - name: MYSQL_DATABASE
            value: "{{ .Values.db.name }}"
          ports:
          - containerPort: 3306
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
          args: ["mysqld", "--character-set-server=utf8", "--collation-server=utf8_general_ci"]

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
        labels:
          app: "{{ template "mariadb.name" . }}"
          component: "db"
          release: {{ .Release.Name | quote }}
          heritage: {{ .Release.Service | quote }}
      spec:
        accessModes:
        {{- range .Values.mariadb.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        storageClassName: {{ .Values.mariadb.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.mariadb.persistence.size | quote }}

