apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mariadb.service.type }}
  clusterIP: {{ .Values.mariadb.service.clusterIP }}
  ports:
    - port: {{ .Values.mariadb.service.port }}
      targetPort: 3306
      protocol: TCP
  selector:
    {{- include "mariadb.selectorLabels" . | nindent 4 }}
