apiVersion: v1
kind: Service
metadata:
  name: {{ include "rod3.fullname" . }}
  labels:
    {{- include "rod3.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "rod3.selectorLabels" . | nindent 4 }}
