{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rod3.serviceAccountName" . }}
  labels:
{{ include "rod3.labels" . | nindent 4 }}
{{- end -}}
