apiVersion: v1
kind: Service
metadata:
  name: {{ include "smtpmock.fullname" . }}
  labels:
    {{- include "smtpmock.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: smtp
      protocol: TCP
      name: smtp
  selector:
    {{- include "smtpmock.selectorLabels" . | nindent 4 }}
